### ISSUE TITLE
read_products scope throws OmniAuth::Strategies::OAuth2::CallbackError

### ISSUE THREAD

**Issue by Random4405** [Shopify/omniauth-shopify-oauth2#65]
When I try to install an application with this scope (`read_products` or `write_products`), I get an error:

```
OmniAuth::Strategies::OAuth2::CallbackError
invalid_scope | Scope does not match, it may have been tampered with.
```
This happens with all my applications with this scopes

Here is the full trace:
```
Started GET "/auth/shopify" for 37.17.20.204 at 2018-05-02 15:34:29 +0300
Cannot render console from 37.17.20.204! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
I, [2018-05-02T15:34:29.128429 #10178]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2018-05-02T15:34:29.128967 #10178]  INFO -- omniauth: (shopify) Request phase initiated.
Started GET "/auth/shopify/callback?code=*CODE*&shop=*SHOP*&state=*STATE*&timestamp=1525264472" for 37.17.20.204 at 2018-05-02 15:34:32 +0300
Cannot render console from 37.17.20.204! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
I, [2018-05-02T15:34:32.491714 #10178]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2018-05-02T15:34:32.492135 #10178]  INFO -- omniauth: (shopify) Callback phase initiated.
E, [2018-05-02T15:34:33.271535 #10178] ERROR -- omniauth: (shopify) Authentication failure! invalid_scope: OmniAuth::Strategies::OAuth2::CallbackError, invalid_scope | Scope does not match, it may have been tampered with.

OmniAuth::Strategies::OAuth2::CallbackError (invalid_scope | Scope does not match, it may have been tampered with.):

appsignal (2.5.1) lib/appsignal/rack/rails_instrumentation.rb:30:in `call_with_appsignal_monitoring'
appsignal (2.5.1) lib/appsignal/rack/rails_instrumentation.rb:15:in `call'
```

**Comment by peterjm** [comment]
@Random4405 we're looking into this; we're experiencing the same problem on some of our Shopify-owned apps, too. I'll let you know when the fix is done.

**Comment by peterjm** [comment]
This should be fixed now.

**Comment by Random4405** [comment]
Thanks!

**Comment by Iqlaas** [comment]
![screen shot 2018-07-24 at 5 56 35 pm](https://user-images.githubusercontent.com/10087314/43131548-e4b73350-8f6b-11e8-85a0-0190f78bdd11.png)

Hi. Is it happening again ?

**Comment by johnsampson** [comment]
This issue resulted when `strategy.options[:scope]` in omniauth.rb was not in sync with the main auth scope config.  Make sure they match and try again.
