### ISSUE TITLE
build_access_token raises un-rescued Faraday error that bubble to apps using shopify-app

### ISSUE THREAD

**Issue by ewalk153** [Shopify/omniauth-shopify-oauth2#79]
We expect that the underlying omniauth gem will reliably raise a connection errors with a `fail` when we call `build_access_token`:
https://github.com/Shopify/omniauth-shopify-oauth2/blob/f5a42a4ab7d17f98147d67db983a74cd887a2df6/lib/omniauth/strategies/shopify.rb#L120

https://github.com/omniauth/omniauth-oauth2/blob/10e1a42c7a49ad4488fe9085f814681e8848fbf6/lib/omniauth/strategies/oauth2.rb#L66-L83
```ruby
      def callback_phase # rubocop:disable AbcSize, CyclomaticComplexity, MethodLength, PerceivedComplexity
        error = request.params["error_reason"] || request.params["error"]
        if error
          fail!(error, CallbackError.new(request.params["error"], request.params["error_description"] || request.params["error_reason"], request.params["error_uri"]))
        elsif !options.provider_ignores_state && (request.params["state"].to_s.empty? || request.params["state"] != session.delete("omniauth.state"))
          fail!(:csrf_detected, CallbackError.new(:csrf_detected, "CSRF detected"))
        else
          self.access_token = build_access_token
          self.access_token = access_token.refresh! if access_token.expired?
          super
        end
      rescue ::OAuth2::Error, CallbackError => e
        fail!(:invalid_credentials, e)
      rescue ::Timeout::Error, ::Errno::ETIMEDOUT => e
        fail!(:timeout, e)
      rescue ::SocketError => e
        fail!(:failed_to_connect, e)
      end
```

The underlying connection can close, which normally raises a Faraday ConnectionFailed error.
```ruby
vendor/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill': end of file reached (Faraday::ConnectionFailed)
    from vendor/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
    from vendor/ruby-2.5.3/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
    from vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
    from vendor/ruby-2.5.3/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
[snip]
```

Recently, we saw tier 2 apps getting blocked by our ABS service which stress a new failure mode to these request.

https://app.bugsnag.com/shopify/theme-store-cloud/errors/5c865049d2ca02001925a0ff?filters[event.since][0][type]=eq&filters[event.since][0][value]=3h&filters[error.status][0]=new

Options that I I see:
1. We rescue in the `omniauth-shopify-oauth2` as the oauth code path in `shopify-app` is merely asking for a token and shouldn't care about why it failed
2. We push this concern up to the superclass `omniauth-oauth2` to make sure Faraday errors are rescued
3. We let it bubble up to `shopify-app` and rescue it there

In any event, this should not reach Shopify apps without being first handled.

**Comment by jeffblake** [comment]
On a related note, `build_access_token` can also fail and raise a `OAuth2::Error` when the response code is 400. For example, "Oauth error invalid_request: The authorization code was not found or was already used"

This doesn't happen often in my app, but it would be nice not to show the user a 500 error page.

Gist of the full HTML response from shopify: https://gist.github.com/jeffblake/13b3c8fe3100f76b0b115a0024029333

Stack trace:

<img width="1493" alt="Screen Shot 2019-12-09 at 5 56 41 PM" src="https://user-images.githubusercontent.com/620564/70488524-cda49080-1aad-11ea-852b-33b1b377b27d.png">
